### ISSUE TITLE
src/coin/CoinUtils/CoinMessageHandler.cpp:766:35: error:  format not a string literal and no format arguments

### ISSUE THREAD

**Issue by jonathonf** [ogdf/ogdf#24]
Compiling on Ubuntu 16.04 with GCC 5.4.

```bash
src/coin/CoinUtils/CoinMessageHandler.cpp:766:35: error:  format not a string literal and no format arguments [-Werror=format-security]
      sprintf(messageOut_,format_+2);
```

I'm not sure what `format_+2`is accomplishing or whether something as naive as 

```c++
sprintf(messageOut_,"%s",format_+2);
```
or even
```c++
sprintf(messageOut_,"%s");
```

would fix.

**Comment by sbeyer** [comment]
Hi,

that's a bit odd. Do you compile OGDF with standard compile flags?

We use `-Werror` by default (which makes gcc and clang treat warnings as errors) but AFAIK only for the OGDF and not for COIN (because we are not maintaining COIN). Could you add `-Wno-error=format-security` to the CMAKE_CXX_FLAGS in your CMake configuration?

**Comment by jonathonf** [comment]
I'm trying to package OGDF for Ubuntu 16.04; that error shows up with the default `debuild`/`debhelper` build options. Pretty sure the extra flag will silence the error but I can verify it if you want; not sure how useful it would be if it's no longer being maintained?

For what I'm doing, if COIN isn't maintained and isn't needed for OGDF I'll just drop it and repackage the source archive.

**Comment by sbeyer** [comment]
COIN is not maintained by *us*. It is maintained by the COIN developers but we include it to make installation easy (because COIN itself can be pretty complex to install and use). When we find the time, we are going to update the included COIN package (I planned to do this for a long time but ... other priorities). However, I am not very optimistic that it solves the `sprintf` issue.

When I am going to update COIN, I also want to add a CMake switch which makes it easy to use the system's COIN package (when installed), which should be the way to go for Debian/Ubuntu packages.

Note that there will also be a snapshot update which adds a `OGDF_WARNING_ERRORS` switch to enable or disable the `-Werror` behavior, however, I think, your `-Werror` flag seems to come from debuild or debhelper. Have you enabled [`DEB_BUILD_HARDENING`](https://wiki.debian.org/Hardening#DEB_BUILD_HARDENING_FORMAT_.28gcc.2Fg.2B-.2B-_-Wformat_-Wformat-security_-Werror.3Dformat-security.29)?

**Comment by jonathonf** [comment]
> COIN is not maintained by _us_

Ah, righty. :)

> Have you enabled DEB_BUILD_HARDENING?

I haven't enabled it via my `debian/rules`; I don't think that's enabled by default on 16.04 (IIRC it is default on Ubuntu Artful and Debian Stretch), but I'll check.

> When I am going to update COIN, I also want to add a CMake switch which makes it easy to use the system's COIN package (when installed), which should be the way to go for Debian/Ubuntu packages.

Makes a lot of sense - I can see a number of COIN packages exist (though it is a large number of packages... I might be looking down a rabbit hole 😁).

**Comment by sbeyer** [comment]
> > Have you enabled DEB_BUILD_HARDENING?
> 
> I haven't enabled it via my debian/rules; I don't think that's enabled by default on 16.04 (IIRC it is default on Ubuntu Artful and Debian Stretch), but I'll check.

That was the only clue I found that would make sense.

> > When I am going to update COIN, I also want to add a CMake switch which makes it easy to use the system's COIN package (when installed), which should be the way to go for Debian/Ubuntu packages.
> 
> Makes a lot of sense - I can see a number of COIN packages exist (though it is a large number of packages... I might be looking down a rabbit hole 😁).

Yes, that's one of the issues with COIN when one wants to use it (and one of the reasons why we include it directly). A lot of packages with a lot of confusing names.

**Comment by 2maz** [comment]
see https://github.com/ogdf/ogdf/pull/51 to close and fix this issue

**Comment by sbeyer** [comment]
Thanks a lot.
