### ISSUE TITLE
Any plan to have a stable release soon?

### ISSUE THREAD

**Issue by navidR** [ogdf/ogdf#31]
I am writing a port of ogdf for Microsoft/vcpkg. But since the latest stable version (2015.3) is not based on CMake that is making my job very hard. Do you have any plan to have a stable release soon?

**Comment by sbeyer** [comment]
Yes and no. A stable release is planned but there are some changes to come before that release. However, priorities by the main OGDF developers are different at the moment.

Since we usually recommend every user to use the latest snapshots, I'd also recommend to write that vcpkg support for the latest snapshot.

**Comment by sbeyer** [comment]
Catalpa has been released btw.
