### ISSUE TITLE
libraries missing

### ISSUE THREAD

**Issue by GiannisNemp** [ogdf/ogdf#46]
```
Could NOT find LIBDW (missing:  LIBDW_LIBRARY LIBDW_INCLUDE_DIR) 
Could NOT find LIBBFD (missing:  LIBBFD_LIBRARY LIBDL_LIBRARY LIBDL_INCLUDE_DIR) 
Could NOT find LIBUNWIND (missing:  LIBUNWIND_LIBRARY LIBUNWIND_INCLUDE_DIR) 
Performing Test compiler_has_pretty_function
Performing Test compiler_has_pretty_function - Failed
The default target builds OGDF (and dependencies like COIN).
Because DOC_INSTALL is set, it also generates the OGDF documentation (in-source).

Other important targets:
        OGDF: build OGDF library only
         doc: build doxygen documentation (in-source)
       tests: build tests
    examples: build examples
   build-all: build OGDF, tests, examples
```
This is the error I get from Cmake.  I am trying to build OGDF in windows. OGDF,COIN and bandit-runner libs are build successfully. However, when I try to build everything in visual studio the build-all.lib is not found (indeed cmake failed to create it). Do they exist somewhere for windows? Do I need to generate them? It is not clear on how to face this error.

**Comment by sbeyer** [comment]
This is no error. The libraries mentioned here (that could not be found) as well as the compiler feature test (that failed) are only necessary for additional debugging features.

I think the Visual Studio generators by CMake generates a file called `OGDF-PROJECT.sln` which you can open in Visual Studio. But I am not 100% sure. Hope that helps.

**Comment by GiannisNemp** [comment]
Thanks for the quick answer. I think we are getting close to the solution.

```
1>------ Build started: Project: doc-check, Configuration: Release Win32 ------
2>------ Skipped Build: Project: doc, Configuration: Release Win32 ------
2>Project not selected to build for this solution configuration 
3>------ Skipped Build: Project: build-all, Configuration: Release Win32 ------
3>Project not selected to build for this solution configuration 
4>------ Skipped Build: Project: INSTALL, Configuration: Release Win32 ------
4>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 0 failed, 61 up-to-date, 3 skipped ==========
```

This is the output I got (after some debugging). What should I expect the sln to build to? Some exe? And where should it be located? 3/65 projects inside the solution failed to build correctly, are those the additional features you mentioned? Any idea?

**Comment by sbeyer** [comment]
> What should I expect the sln to build to?

At least some OGDF library files, i.e., look out for a file ending with `.lib` (static case) or `.dll` (in case you compile as a shared library).

> Some exe?

It looks like you have compiled the examples as well as the tests, so look out for exe files prefixed with `ex-` (these are examples) and a `tests.exe` (or, depending on your configuration, exe files prefixed with `test-`)

> And where should it be located?

If you haven't done some specific configuration, the library files are probably in the project's root (not quite sure, though; there may also be a Visual-Studio-generated subdirectory).

> 3/65 projects inside the solution failed to build correctly, are those the additional features you mentioned?

No, they're just for better debugging output when things fail. The three targets that were skipped, are `doc`, `build-all` and `INSTALL`, which is probably because you have built the "ALL" standard target (which equals the `build-all` custom target more or less). Hence there is nothing to worry about here.
