### ISSUE TITLE
[Cmake] Target files not available.

### ISSUE THREAD

**Issue by huypn12** [ogdf/ogdf#48]
In file ogdf-config.cmake
```# This file is to be included by user code using find_package()

include("${CMAKE_CURRENT_LIST_DIR}/CoinTargets.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/OgdfTargets.cmake")

set(OGDF_INCLUDE_DIRS $<TARGET_PROPERTY:OGDF,INTERFACE_INCLUDE_DIRECTORIES>)
```

CoinTargets.cmake and OgdfTargets.cmake files are not available.

**Comment by sbeyer** [comment]
These files should be generated by the install target.

**Comment by huypn12** [comment]
> These files should be generated by the install target.

Sorry, that was my bad. I used "ogdf" library target rather that "OGDF". CMake add_subdirectory works fine now.

**Comment by piratadelcaribe** [comment]
> These files should be generated by the install target.

I'm new to CMake and I am having the same problem as above. I am using the template provide it as my root CMakeLists.txt file
Could you describe more what you mean by **install target**?

```
cmake_minimum_required(VERSION 3.1)
project(ogdf-user-example CXX)

set(OGDF_CONFIG_SEARCH_PATH CACHE PATH "")

find_package(OGDF CONFIG PATHS ${OGDF_CONFIG_SEARCH_PATH})
if(NOT OGDF_FOUND)
  message(FATAL_ERROR "No OGDF configuration for CMake has been found. "
    "Please set OGDF_CONFIG_SEARCH_PATH such that ogdf-config.cmake (generated by your OGDF build) can be found.")
endif()

add_executable(check-build-mode check-build-mode.cpp)
target_include_directories(check-build-mode PRIVATE ${OGDF_INCLUDE_DIRS})
target_link_libraries(check-build-mode OGDF)
```
I am in Windows using Visual Studio 2019. My final goal is to have a simple main.cpp that calls functions from OGDF

**Comment by milsen** [comment]
Before you can use the OGDF in your own projects, the OGDF has to be built (and potentially installed).

Do to so, we first run [CMake](https://cmake.org/runningcmake/). Afterwards we have several build targets available: On Linux, these can be built with `make`, e.g. `make install`. On Windows, however, the most "user-friendly" way is probably some kind of button in your IDE, that is, in Visual Studio. Remember that you should first use the BUILD_ALL and then the INSTALL target.
Since I do not use Windows myself, I only have limited knowledge of how this all looks like in practice. Maybe this [video](https://www.youtube.com/watch?v=LxHV-KNEG3k) could help you.

Once the OGDF is installed, you can include OGDF headers in your main.cpp as long as you link your executable with the OGDF. The example CMakeLists.txt that you mention does this via `target_link_libraries`. Of course you have to replace the `check-build-mode.cpp` in the CMakeLists.txt by `main.cpp` for everything to work.

**Comment by piratadelcaribe** [comment]
Thank you @milsen! I learned a lot from CMake trying to include the OGDF. I was not sure what the INSTALL target produced, the video you linked is good and help me clarifying this. I can now build my own user code by manually adding the corresponding `Property Sheet` or better by using the CMakeLists.txt template and the OGDF directory generated after building INSTALL.
