### ISSUE TITLE
Please don't use the same numerical version for two different releases.

### ISSUE THREAD

**Issue by akesandgren** [ogdf/ogdf#80]
The numerical part of a release version MUST be distinct from any other version and strictly increasing. That's the only certain way to know what release is the newest one.
So please use full date as version if you want to use date-based versioning.

**Comment by milsen** [comment]
I understand that using the full date would be necessary if we had two different releases in the same month. But that has never been the case so far.
Did we miss changing the version number somewhere? Where exactly?
Maybe there is some confusion because the previous two releases had the numbers 202**0**.02 and 202**2**.02 respectively; they look very similar.

**Comment by akesandgren** [comment]
Ah yes, I was slightly blind when reading the Catalpa version number, sorry about this. Shouldn't do too much stuff before first coffee...
