### ISSUE TITLE
[Question] Face recognition in Planar Graphs

### ISSUE THREAD

**Issue by DANDROZAVR** [ogdf/ogdf#88]
Dear OGDF Community,
Recently I was experimenting with OGDF function for planar graphs, such as "computeFaces" in "ConstCombinatorialEmbedding" or finding "PlanarStraightLayout" for planar graphs too. The second seems to work well, but the first isn't. Below I provide the sample of the code, the planar graph I'm processing, and the 2dim points assigned to the graph.

This code says there are two faces in that graph, "0 1 4 0 3 6 2 5 3 0 2 6 5 2" and "0 4 1 0 6 3 5 6", which, obviously, isn't true. So my question is, are there some bugs in the OGDF code that produces that output, or am I not using it correctly? Documentation, as typical, says nothing :/

I'm using the latest version of OGDF (Dogwood)

![image](https://github.com/ogdf/ogdf/assets/48687268/653cc473-3186-4935-aca2-f7073291c993)

The edges:
1 2
1 3
1 4
2 5
1 5
4 6
3 6
6 7
7 3
7 4
7 1

Sample code:
https://ideone.com/VzX0De

Or:
https://pastebin.com/PC0MwMy8

Or:
```#include <iostream>
#include <ogdf/basic/Graph.h>
#include <ogdf/planarlayout/PlanarStraightLayout.h>
#include <ogdf/basic/CombinatorialEmbedding.h>
#include <ogdf/basic/GridLayout.h>

int main() {
    // Create a graph
    ogdf::Graph graph;
    auto graphAttributes = ogdf::GraphAttributes(graph);
    // Add nodes to the graph
    //ogdf::node v0 = graph.newNode();
    ogdf::node v1 = graph.newNode();
    ogdf::node v2 = graph.newNode();
    ogdf::node v3 = graph.newNode();
    ogdf::node v4 = graph.newNode();
    ogdf::node v5 = graph.newNode();
    ogdf::node v6 = graph.newNode();
    ogdf::node v7 = graph.newNode();

    // Add edges to the graph
    graph.newEdge(v1,v2);
    graph.newEdge(v1,v3);
    graph.newEdge(v1,v4);
    graph.newEdge(v2,v5);
    graph.newEdge(v1,v5);
    graph.newEdge(v4,v6);
    graph.newEdge(v3,v6);
    graph.newEdge(v6,v7);
    graph.newEdge(v3,v7);
    graph.newEdge(v4,v7);
    graph.newEdge(v1,v7);

    ogdf::PlanarStraightLayout layout;
    layout.call(graphAttributes);
    ogdf::CombinatorialEmbedding combEmbending = ogdf::CombinatorialEmbedding(graph);
    combEmbending.computeFaces();

    auto elem = combEmbending.faces;
    std::vector<std::vector<ogdf::node>> allFaces;
    for (auto &x : elem) {
        auto first = x->firstAdj();
        std::vector <ogdf::node> all;
        for (auto smth : x->entries) {
            auto y = smth;
            all.push_back(y->theNode());
            //std::cout << y->isSource() << ' ';
        }
        allFaces.push_back(all);
    }

    std::cout << "SEE\n";
    for (auto i : allFaces) {
        for (auto j : i) std::cout << j->index() << " ";
        std::cout << '\n';
    }
    std::cout << '\n';

    // Output the coordinates of each node
    std::vector<std::string> arr;
    for (ogdf::node n : graph.nodes) {
        ogdf::DPoint pos = graphAttributes.point(n);
        std::cout << "Node " << n->index() << " Position: (" << pos.m_x << ", " << pos.m_y << ")" << std::endl;
        arr.push_back(std::to_string(pos.m_x) + " " + std::to_string(pos.m_y));
    }
    for (auto &e: graph.edges) {
        auto nodes = e->nodes();
        auto point1 = graphAttributes.point(nodes[0]);
        auto point2 = graphAttributes.point(nodes[1]);
        std::cout << point1.m_x << " " << point1.m_y << " " << point2.m_x << " " << point2.m_y << '\n';
    }
    for (auto i : arr)
        std::cout << i << '\n';
    return 0;
}

**Comment by milsen** [comment]
Dear Andrei,

1. Your code did not compile for me, so I made some changes.
The most important one is the constructor calls. If you use `operator=`, it will create a CombinatorialEmbedding and then copy it to the variable `combEmbedding` (you did something similar for `Graph`). That might usually be optimized by the compiler, but in this case, CombinatorialEmbedding had no copy constructor, so the code did not compile.
You also do not need to call `computeFaces()` separately, the constructor of `CombinatorialEmbedding` does that automatically.

```
// use this
ogdf::CombinatorialEmbedding combEmbedding(graph);

// not this
ogdf::CombinatorialEmbedding combEmbedding = ogdf::CombinatorialEmbedding(graph);
combEmbedding.computeFaces();
```

2. If you write more complex code, it's probably best if you compile everything in Debug mode and later switch to Release mode (when everything works). That way you get notified of failed assertions etc. In this case, the code segfaults with "Assertion `G.representsCombEmbedding()` failed.".

3. To explain this assertion: `Graph` itself actually carries an embedding itself since it contains, for every node, a list of adjEntries of incident edges. The order of this list of adjEntries induces the embedding. The embedding might not actually be a planar embedding because a) the graph itself may not be planar, or b) the adjEntries are not ordered correctly yet (this is your case).
The CombinatorialEmbedding, however, expects these adjEntries to be ordered correctly already in order for it to compute the faces:

```
/**
  * \brief Creates a combinatorial embedding of graph \p G.
  *
  * \pre Graph \p G must be embedded, i.e., the adjacency lists of its nodes
  *      must define an embedding.
  */
```

The ordering can be done with e.g. `planarEmbed()`.
So call this function before creating the CombinatorialEmbedding.

4. Now you might want to output the vertices of the faces and have a nice drawing of the same layout. Here, there is an actual problem. You see, by default, `PlanarStraightLayout` and friends compute completely new embeddings, i.e. ones that do not match the embedding of the Graph. Hence, the output face nodes and the drawing would potentially not match each other.
Normally, you could use `PlanarStraightLayout::callFixEmbed()` to use the embedding of the Graph. However, in `PlanarStraightLayout`, there is a bug that breaks this (see https://groups.google.com/g/ogdf/c/U6ljY74k4M8/m/P4JJqijdCwAJ ). So I use `SchnyderLayout::callFixEmbed()` instead.


<details open>
<summary>Putting it all together:</summary>
<br>


```
#include <ogdf/basic/Graph.h>
#include <ogdf/basic/graph_generators.h>
#include <ogdf/fileformats/GraphIO.h>
#include <ogdf/planarlayout/SchnyderLayout.h>
#include <ogdf/basic/CombinatorialEmbedding.h>
#include <ogdf/basic/extended_graph_alg.h>

int main() {
	// Create a graph.
	ogdf::Graph graph;
	ogdf::GraphAttributes graphAttributes(graph, ogdf::GraphAttributes::all);
	ogdf::customGraph(graph, 7, // cool function for quick graph creation
			{{0,1},
			{0,2},
			{0,3},
			{1,4},
			{0,4},
			{3,5},
			{2,5},
			{5,6},
			{2,6},
			{3,6},
			{0,6}});

	// Planar embed + CombinatorialEmbedding.
	bool isPlanar = planarEmbed(graph);
	if (!isPlanar) {
		std::cout << "Graph not planar, something went wrong!" << std::endl;
	}
	ogdf::CombinatorialEmbedding combEmbedding(graph);

	// Call SchnyderLayout but use the embedding that we just computed
	// via callFixEmbed.
	// Otherwise SchnyderLayout will compute its own embedding, which might not
	// correspond to the one we computed (and then you get a mismatch between
	// output faces and drawn layout).
	ogdf::SchnyderLayout layout;
	layout.callFixEmbed(graphAttributes);
	for (ogdf::node v : graph.nodes) {
		graphAttributes.label(v) = std::to_string(v->index());
	}
	graphAttributes.scale(7,false);
	ogdf::GraphIO::write(graphAttributes, "github-issue-88.svg");

	std::vector<std::vector<ogdf::node>> allFaces;
	for (auto f : combEmbedding.faces) {
		std::vector <ogdf::node> all;
		for (auto adj : f->entries) {
			all.push_back(adj->theNode());
		}
		allFaces.push_back(all);
	}

	// NOTHING CHANGED BELOW THIS LINE.

	std::cout << "SEE\n";
	for (auto i : allFaces) {
		for (auto j : i) std::cout << j->index() << " ";
		std::cout << '\n';
	}
	std::cout << '\n';

	// Output the coordinates of each node
	std::vector<std::string> arr;
	for (ogdf::node n : graph.nodes) {
		ogdf::DPoint pos = graphAttributes.point(n);
		std::cout << "Node " << n->index() << " Position: (" << pos.m_x << ", " << pos.m_y << ")" << std::endl;
		arr.push_back(std::to_string(pos.m_x) + " " + std::to_string(pos.m_y));
	}
	for (auto &e: graph.edges) {
		auto nodes = e->nodes();
		auto point1 = graphAttributes.point(nodes[0]);
		auto point2 = graphAttributes.point(nodes[1]);
		std::cout << point1.m_x << " " << point1.m_y << " " << point2.m_x << " " << point2.m_y << '\n';
	}
	for (auto i : arr)
		std::cout << i << '\n';
	return 0;
}
```
</details>

**Comment by DANDROZAVR** [comment]
Dear Max,
Thank you a lot for this useful tips and bug fixes. I compile the code with c++20/17 so I haven't the first error. However, I wasn't able to reproduce the assertion error you mentioned in your second point. I compiled the code using g++ with the flags -g, -ggdb, and -O0 for debugging purposes, but the error did not occur.

To help me further troubleshoot similar issues, could you please share the exact debug configuration flags you used? 

Thank you once again for your assistance.

**Comment by DANDROZAVR** [comment]
Regarding the bug you have mentioned in google groups (fix in EmbedderBCTreeBase.h), is it still working? I tried it and the program is still crashing

**Comment by milsen** [comment]
> I compiled the code using g++ with the flags -g, -ggdb, and -O0 for debugging purposes, but the error did not occur.
> To help me further troubleshoot similar issues, could you please share the exact debug configuration flags you used?

Instead of compiling everything by hand, we use [CMake](https://cmake.org/runningcmake/) to build the OGDF.
And to get a real OGDF debug build, you have to set the CMake variable `CMAKE_BUILD_TYPE` to `Debug`.
For more information, please read: https://github.com/ogdf/ogdf/blob/master/doc/build.md

> Regarding the bug fix you have mentioned in google groups (fix in EmbedderBCTreeBase.h), is it still working? I tried it and the program is still crashing

The bug I mentioned regarding `PlanarAugmentationFix` (and `PlanarStraightLayout::callFixEmbed`) still occurs. It is known but has not been fixed yet.
However, the bug that originally caused that google group discussion, i.e. `EmbedderBCTreeBase` using the wrong external face, should be fixed.

**Comment by DANDROZAVR** [comment]
Got you, thank you a lot!
