### ISSUE TITLE
Using from MetaCarvel

### ISSUE THREAD

**Issue by jesusbvf** [ogdf/ogdf#91]
When using from MetaCarvel:
spqr: OGDF/include/ogdf/basic/NodeArray.h:184: T& ogdf::NodeArray<T>::operator[](ogdf::node) [with T = int; ogdf::node = ogdf::NodeElement*]: Assertion `v->graphOf() == m_pGraph' failed.
Aborted (core dumped)

**Comment by milsen** [comment]
The assertion means that some NodeArray is initialized with a graph G1, but then you then try to use a node from a different graph G2 as a key for this NodeArray.

Unless you can give more information on the exact code that causes the error (some lines from [this file](https://github.com/marbl/MetaCarvel/blob/master/spqr.cpp)?), I assume that this may be a problem of MetaCarvel rather than an internal inconsistency of the OGDF.
